apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-access
  labels:
    app: data-access
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: data-access
  template:
    metadata:
      labels:
        app: data-access
    spec:
      containers:
      - name: data-access
        image: data-access
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          
---

apiVersion: v1
kind: Service
metadata:
  name: data-access
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: data-access