apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-provider
  labels:
    app: exercise-provider
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: exercise-provider
  template:
    metadata:
      labels:
        app: exercise-provider
    spec:
      containers:
      - name: exercise-provider
        image: exercise-provider
        imagePullPolicy: Never
        ports:
        - containerPort: 2000
          
---

apiVersion: v1
kind: Service
metadata:
  name: exercise-provider
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 2000
      protocol: TCP
      targetPort: 2000
  selector:
    app: exercise-provider