apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    app: user-db
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - name: user-db
        image: postgres
        ports:
        - containerPort: 5432
        lifecycle:
          postStart: 
            exec:
              command: ["/bin/sh", "-c", "sleep 20 && PGPASSWORD=passw0rd124 psql -w -d user_data_db -U user -c 'CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name TEXT, about TEXT); CREATE TABLE IF NOT EXISTS exercises (id SERIAL PRIMARY KEY, name TEXT, xp INT, description TEXT); CREATE TABLE IF NOT EXISTS completed_exercises (ex_id SERIAL REFERENCES exercises, user_id SERIAL REFERENCES users);'"]
        env:
        - name: POSTGRES_DB
          value: user_data_db
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: passw0rd124
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: user-db-pvc
      volumes:
      - name: user-db-pvc
        persistentVolumeClaim:
          claimName: user-db-pvc
          
---

apiVersion: v1
kind: Service
metadata:
  name: user-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: user-db