apiVersion: v1
kind: PersistentVolume
metadata: 
  name: user-db-pv
  labels:
    type: local
spec:
  storageClassName: user-db-class
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/user-db"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: user-db
  name: user-db-pvc
spec:
  storageClassName: user-db-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi