apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-verifier
  labels:
    app: exercise-verifier
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: exercise-verifier
  template:
    metadata:
      labels:
        app: exercise-verifier
    spec:
      containers:
      - name: exercise-verifier
        image: exercise-verifier
        imagePullPolicy: Never
        ports:
        - containerPort: 10000
          
---

apiVersion: v1
kind: Service
metadata:
  name: exercise-verifier
spec:
  type: ClusterIP
  ports:
    - port: 10000
      protocol: TCP
      targetPort: 10000
  selector:
    app: exercise-verifier